docs/src/schelling.md

Hello - as I was reading through the documentation I thought to do some light refactoring on this page. I fixed a handful of typos, rewrote the first sentence on the page, broke up some of the larger paragraphs for better readability and turned one paragraph into a bullet list.

Light refactoring to schelling.md documentation page

---

README.md
docs/src/index.md

add logo, mention juliadynamics

---

benchmark/forest_fire/forest_fire.jl
benchmark/forest_fire/run.jl
docs/src/boltzmann_example01.md
docs/src/forest_fire.md
docs/src/tutorial.md
examples/boltzmann_wealth_distribution.jl
examples/boltzmann_wealth_distribution_with_grid.jl
examples/forest_fire.jl
examples/schelling.jl
examples/schelling_distributed.jl
src/Agents.jl
src/CA1D.jl
src/CA2D.jl
src/core/agent_space_interaction.jl
src/core/model.jl
src/core/space.jl
src/simulations/data_collector.jl
src/simulations/parallel.jl
src/simulations/step.jl
test/forest_fire_defs.jl
test/schelling_defs.jl
test/try_new_api.jl

This pr implements what was discussed in #53 . Closes #53 
@kavir1698 after you merge this I'll leave it to you to update the tests and make one appropriate benchmarking file... I suddendly got quite a bit of stuff on my desk.
After these updates we can move forwards with testing and benchmarking the new storage type(s) for agents

new type for models

---

CHANGELOG.md
src/simulations/data_collector.jl
src/simulations/step.jl
test/data_collector_test.jl

This answers #102.
I have not updated the version, so that we can merge merge this with #101 into v2.1.0

Conditionally stop simulations

---

src/core/agent_space_interaction.jl

Better docs for add_agent!

---

Project.toml
docs/make.jl
docs/src/api.md
docs/src/tutorial.md
examples/wealth_distribution.jl
examples/wright-fisher.jl
src/Agents.jl
src/core/agent_space_interaction.jl
src/simulations/sample.jl
test/api_tests.jl

A common task during agent-based modeling, at least in biology and ecology, is replacing the agents with a sample of them. Since doing that with a dictionary is more difficult than an array, I have written this `sample!` function.

Add sample! function

---

Project.toml
src/core/agent_space_interaction.jl
test/runtests.jl
test/space_test.jl

Add agent bug

---

examples/HK.jl

As discussed in https://github.com/JuliaDynamics/Agents.jl/issues/123 I have added a function barrier to examples/HK.jl `model_step!`. I only changed this line because I was afraid of messing with other files unwillingly.

In which I fix  HK.jl example

---

README.md
docs/src/index.md
docs/src/tutorial.md
examples/forest_fire.jl
test/benchmark/DynamicGrids/agents.jl
test/benchmark/DynamicGrids/dynamicgrids.jl

C.f. https://github.com/cesaraustralia/DynamicGrids.jl/issues/10

Benchmark versus dynamic grid and mentioning

---

Project.toml
examples/continuous_space.jl
src/Agents.jl
src/core/continuous_space.jl
src/core/model.jl
src/core/space.jl

Ali merge please if everything is a-ok

organize and generalize continuous space

---

examples/social_distancing.jl

This is a disease spread model inspired by [this article](https://www.washingtonpost.com/graphics/2020/world/corona-simulator/) and our SIR model. What I show here is agents moving in a continuous space. I used a SQL data structure for quickly finding agents in a given area. 
To do:
[] Add some explanations.

Social distancing model

---

examples/continuous_space.jl
src/core/continuous_space.jl

Adds periodicity for continuous space

periodicity in continuous space

---

docs/src/api.md
src/core/agent_space_interaction.jl
src/core/continuous_space.jl
src/core/model.jl
src/core/space.jl
src/simulations/sample.jl

Improves the API and documentation a lot. It is crazy how much cleaner the source code becomes when one realizes which functions should be calling which. Have a look at the source around `add_agent!` for continuous and discrete space and the continuous case is so much cleaner.

Model-Agent interaction API improvement / docs

---

src/core/continuous_space.jl
test/continuousSpace_tests.jl
test/runtests.jl

Some tests on continuous space

---

CHANGELOG.md
docs/src/api.md
docs/src/index.md
src/core/agent_space_interaction.jl
src/core/continuous_space.jl
src/core/space.jl
test/continuousSpace_tests.jl

After we merge #150, I'll update this and add tests for space_neighbors for both discrete and continuous space.
Good news: this is not even breaking, because `node_neighbors` does a different thing and we can keep it!

space_neighbors functionality

---

src/core/agent_space_interaction.jl
src/simulations/sample.jl
test/api_tests.jl

Fix a bug in sample!

---

CHANGELOG.md
src/core/continuous_space.jl
test/continuousSpace_tests.jl

allow both metrics

---

src/core/continuous_space.jl
test/space_test.jl

Remove missing union in collect_ids

---

CHANGELOG.md
docs/src/api.md
examples/HK.jl
examples/forest_fire.jl
examples/schelling.jl
examples/sir.jl
examples/social_distancing.jl
examples/wealth_distribution.jl
examples/wright-fisher.jl
src/CA1D.jl
src/CA2D.jl
src/simulations/collect.jl
src/simulations/paramscan.jl
test/benchmark/mesa/run.jl
test/collect_tests.jl

Housecleaning aspects for the alterations #191.

Keyword changes and CHANGELOG

---

CHANGELOG.md
docs/make.jl
examples/daisyworld.jl
src/simulations/collect.jl

Reasons:
1. It's pretty awesome
2. Closes #221 via discussion in `run!`

Daisyworld

---

src/core/continuous_space.jl
test/continuousSpace_tests.jl

fix interact based on #220

---

src/core/model.jl

Add note on sharing spaces

---

src/core/continuous_space.jl
test/collisions_tests.jl
test/continuousSpace_tests.jl

Reverts JuliaDynamics/Agents.jl#225

Revert "Extend interacting pairs"

---

examples/social_distancing.jl
src/core/continuous_space.jl
test/collisions_tests.jl
test/continuousSpace_tests.jl

Extensions for #220. Replacement for #225.

Interacting Pairs

---

src/core/agent_space_interaction.jl
src/simulations/sample.jl

Some spring cleaning for `core/agent_space_interaction.jl`.
There were a few `TODO`s in the codebase, which are now sorted:
1. An inefficient empty cells check. We already had a more performant version as a function. d7c952c
2. Complete refactor of add_agent!, basing everything on add_agent_pos! low-level methods
On top of that, I've added a few extra guards, narrowed type scope and altered a number of functions such that they are up to date with our current internal methods.

Agent space updates

---

docs/src/api.md
examples/growing_bacteria.jl
src/core/continuous_space.jl

This as an example system using the continuous space API to model growing bacterial colonies. Bacteria are modeled as two soft disks linked by a spring, whose rest length grows in time. If you have any questions about the model, feel free to ask me.
Technically, there might be room for optimizations; e.g. it lacks good plotting functions. I have left my PyPlot.jl-based debug plotting loop in a block comment for inspiration if anyone wants to add them.

Add growing bacterial colony example

---

docs/Manifest.toml
docs/src/index.md
docs/src/tutorial.md
examples/HK.jl
examples/daisyworld.jl
examples/flock.jl
examples/forest_fire.jl
examples/game_of_life_2D_CA.jl
examples/growing_bacteria.jl
examples/predator_prey.jl
examples/schelling.jl
examples/sir.jl
examples/social_distancing.jl
examples/wealth_distribution.jl
examples/wright-fisher.jl
src/core/continuous_space.jl
src/core/discrete_space.jl

- Added a few additional pieces to introduction
- Dropped development notification
- Spell/grammar check
- Suppress uninformative output in examples
- Small refactors here and there for readability

Prep docs for v3

---

src/core/continuous_space.jl
test/api_tests.jl
test/continuousSpace_tests.jl

add a move_agent! method that uses an argument as the velocity.

---

Project.toml
docs/make.jl
examples/opinion_spread.jl
src/models/Models.jl
src/models/opinion.jl

Here is a new model example I created today, using a model on hash.ai

Create opinion model

---

src/core/continuous_space.jl
test/continuousSpace_tests.jl

Guard for extend in ContinouousSpace

---

docs/src/tutorial.md

Add note about model stepping

---

benchmark/forest.jl
docs/src/api.md
src/spaces/discrete.jl
src/spaces/grid.jl
test/model_access.jl

unfortunately even though I ported most code from TimeseriesPrediction.jl, we can't use it due to design. We still use a lot of stuff though.

clean up grid space

---

docs/src/api.md
examples/schelling.jl
src/simulations/paramscan.jl

This PR improves the docs of `paramscan` and thus addresses #327
Closes #327

Improve documentation of `paramscan`

---

CHANGELOG.md
src/core/model.jl
test/api_tests.jl
test/collisions_tests.jl

This was asked in the Julia slack and it's simple to add.
However, there are two ways to do it: first, you allocate a random permutation of the agent IDs, and iterate through them until you find condition. This way, you can guarantee that you check all agents once, and if no agent satisfies condition, you return `nothing`.
The other way is what I've written. It doesn't allocate, and thus is faster, but if no agent in the model satisfies the condition, then the function will never terminate.
Which one is best?

Random agent with condition

---

CHANGELOG.md
examples/daisyworld.jl
examples/measurements.jl
src/simulations/collect.jl
test/collect_tests.jl

Closes #335. 
No new API, just handling mixed-ABMs as they should have been already.

Implement mixed-ABM collections

---

CHANGELOG.md
src/spaces/grid.jl
test/space_test.jl

This PR satisfies a number of open problems addressed in #359 by adding one additional search pattern into the neighbour search: `r::Vector{Tuple{Int,UnitRange{Int}}}`. This makes searching over specific dimensions with precise distance possible.
Hoods were not the best way of going about this in the end. I attempted to cut down the dimensionality of the hood (in an unpublished branch), but converting back to a set of true `CartesianIndex`s turned out to be impractical.
Searching over 'all' space takes a good deal of time comparatively when looking at `views` of the space. Here's a test case:
```julia
using Agents
using BenchmarkTools                                                                                                                                                      
using …
```

Specified dimension nearest-neighbor search

---

docs/make.jl
examples/daisyworld.jl
examples/daisyworld_matrix.jl
examples/measurements.jl
src/Agents.jl
src/core/model.jl
src/core/schedule.jl
src/core/space_interaction_API.jl
src/models/daisyworld.jl
src/simulations/collect.jl
src/simulations/sample.jl
src/spaces/continuous.jl
src/spaces/discrete.jl
src/spaces/graph.jl
src/spaces/grid.jl
src/spaces/nothing.jl
src/spaces/utilities.jl
test/continuousSpace_tests.jl

Closes #364
First pass at this. Tests run, although there may be some questions as to how daisyworld runs - will see how documentation builds.
Think I covered all of the needed changes. Unsure how much of an improvement this makes are though...

Changing type order in `ABM`

---

CHANGELOG.md
docs/src/tutorial.md
examples/schelling.jl
src/Agents.jl
src/core/agents.jl
src/core/model.jl
src/core/space_interaction_API.jl
src/spaces/continuous.jl
src/spaces/graph.jl
src/spaces/grid.jl
test/api_tests.jl

WIP for #365.
Types and docstrings added, but have not filtered them through examples or anything. No tests done yet, but the results do work out as the docstrings suggest.

Initial pre-defined types

---

docs/make.jl
docs/src/examples.md
docs/src/tutorial.md
examples/opinion_spread.jl
examples/wright-fisher.jl
src/core/model.jl
src/simulations/sample.jl
src/spaces/continuous.jl
src/spaces/discrete.jl
src/spaces/utilities.jl
test/api_tests.jl
test/continuousSpace_tests.jl
test/model_access.jl
test/space_test.jl

This will close out a number of documentation issues when complete. I'm having some issues building docs locally though, so pushing this up to get actions to test the back-referencing. 
Also done some tidying up of never-used small functions and closed some coverage gaps in the tests.

Documentation and test updates

---

src/spaces/openstreetmap.jl
test/osm_tests.jl

If the tests pass on CI here, then this PR will simplify the construction of OSMSpace a little, as well as make things a bit more deterministic with a (very slight) cost in performance.
I'll add some more test coverage before merge if so.

Possible OSMSpace simplification

---

examples/daisyworld.jl
examples/game_of_life_2D_CA.jl
examples/hk.jl
examples/predator_prey.jl
examples/social_distancing.jl
examples/sugarscape.jl
examples/wealth_distribution.jl

* Daisyworld
* Game of Life
* HK opinion dynamics
* Predator-Prey

Updated some examples to use the new plotting backend

---

examples/sugarscape.jl

Uses the new plotting code so that the heatmap and agents plot are in the same video

Updated sugarscape

---

src/spaces/continuous.jl
test/collisions_tests.jl
test/continuousSpace_tests.jl

Closes #320 by fixing up all points outlined in [this comment](https://github.com/JuliaDynamics/Agents.jl/issues/320#issuecomment-766421809).

Pairs by shortest distance, then by scheduler

---

benchmark/compare/Mesa/ForestFire/model.py
benchmark/compare/Mesa/Schelling/model.py
benchmark/compare/Mesa/WolfSheep/model.py

To make the comparison of the speed and LOC more fair. How do I update the benchmark table at https://juliadynamics.github.io/Agents.jl/stable/comparison/#An-in-depth-comparison-of-four-frameworks ?

Mesa benchmark: Remove data collection code

---

Project.toml
src/Agents.jl

Proof of concept for load time decreases (#397).
Using this simple test file
```julia
using Agents
@agent Agent1 GridAgent{2} begin
weight::Float64
end
model = ABM(Agent1, GridSpace((10, 10)))
```
Current master:
```bash
time julia --project=@. test.jl 
julia --project=@. test.jl  25.04s user 1.34s system 105% cpu 25.028 total
```
This PR, with Plot recipes behind a guard
```bash
time julia --project=@. test.jl
julia --project=@. test.jl  20.29s user 1.19s system 107% cpu 20.062 total
```
This was not expected to be large, but it's non-zero & a good starting point.

Less compilation time

---

Project.toml
src/core/agents.jl

Patch @agent to work with types outside of Agents

---

Project.toml
examples/schelling.jl

Documentation hotfix

---

Project.toml
docs/src/tutorial.md
examples/game_of_life_2D_CA.jl
examples/schelling.jl
examples/zombies.jl
src/core/model.jl
src/core/space_interaction_API.jl
src/simulations/step.jl
src/spaces/discrete.jl
src/spaces/openstreetmap.jl

More doc improvements based on a recent tutorial

---

CHANGELOG.md
src/core/model.jl
test/model_access.jl

Allow mutation of model.properties when struct

---

.github/workflows/ci.yml

Drop 1.6 beta testing

---

docs/src/api.md
src/simulations/ensemblerun.jl

Quick fixes for rework of seeds and parallelisation

---

CHANGELOG.md
docs/make.jl
docs/src/api.md
docs/src/interact.md
examples/battle.jl
examples/daisyworld.jl
examples/flock.jl
examples/hk.jl
examples/opinion_spread.jl
examples/predator_prey.jl
examples/schelling.jl
examples/schoolyard.jl
examples/sugarscape.jl
examples/wealth_distribution.jl
src/core/model.jl
src/core/schedule.jl
src/models/battle.jl
src/models/flocking.jl
src/models/hk.jl
src/models/opinion.jl
src/models/predator_prey.jl
src/models/schelling.jl
src/models/sugarscape.jl
src/models/wealth_distribution.jl
src/simulations/paramscan.jl
test/continuousSpace_tests.jl
test/model_access.jl
test/scheduler_tests.jl

schedule: Rename existing schedulers to all have same prefix

---

examples/predator_prey_fast.jl

Better Wolf seed

---

Project.toml
src/simulations/collect.jl

Fixes #500
@ndgnuh, can you confirm this fixes the issue from your point of view?
With your test case, I now get
```julia
adf1 = collect_agg(Schedulers.by_id)
adf2 = collect_normal(Schedulers.by_id)
adf1 == adf2 # True
adf1 = collect_agg(Schedulers.randomly)
adf2 = collect_normal(Schedulers.randomly)
adf1 == adf2 # True
```

Reproducibility regardless of collection details

---

Project.toml
src/core/model.jl

Here is a small suggestion to avoid long and unhelpful ABM printing.

Simpler ABM print

---

docs/src/api.md
examples/schelling.jl
src/submodules/io/jld2_integration.jl

closes #508 
`@eval Main __atexample__named__mockup = $(@__MODULE__) #hide`
Seemed to fix the issue with JLD2 running in Documenter builds in my mockup. Should work here too

Fix Schelling example

---

Project.toml
src/Agents.jl

Use Scratch.jl for update messages

---

Project.toml
docs/Project.toml
docs/src/comparison.md
examples/diffeq.jl
examples/hk.jl
src/models/forestfire.jl
src/spaces/grid.jl
src/submodules/io/csv_integration.jl

Fix up doc drift

---

src/core/space_interaction_API.jl

Created a new PR to keep the revised documentation in a single commit @Datseris.

Documentation update

---

docs/src/api.md
examples/zombies.jl
src/models/zombies.jl
src/spaces/openstreetmap.jl
test/jld2_tests.jl
test/osm_tests.jl

Rename `OSM.intersection` and `OSM.road`

---

Project.toml
docs/src/api.md
src/spaces/openstreetmap.jl
test/osm_tests.jl

Closes #595
I have a plan to make the code a bit more sensible and easy to reason with, which should help with the bugs since there's currently a lot of scope to miss edge cases.

Fix OSM pathfinding

---

examples/rabbit_fox_hawk.jl

Explicitly and directly load ImageMagick

---

src/simulations/step.jl

This allows folks to write `step!(model, agent_step!, sqrt(1729))`

Allow integers to specify stop condition

---

CHANGELOG.md
Project.toml
docs/src/api.md
src/core/space_interaction_API.jl
test/model_creation_tests.jl
test/runtests.jl
test/space_test.jl

Closes #575 
The algorithm used is from https://en.wikipedia.org/wiki/Reservoir_sampling#An_optimal_algorithm
It's a bit better, but not much:
```julia
julia> using Agents
julia> @agent Foo GridAgent{2} begin end
julia> sp = GridSpace((10,10))
julia> model = ABM(Foo, sp)
julia> for i in 1:10, j in 1:10
add_agent!((i, j), model)
end
julia> @benchmark rand($(model).rng, collect(nearby_agents($(model)[1], $(model), 10))) # old method
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):  17.719 μs …  2.865 ms  ┊ GC (min … max): 0.00% … 98.77%
Time  (median):     18.125 μs              ┊ GC (median):    0.00%
Time  (mean ± σ):   20.492 μs ± 60.028 μs  ┊ GC (mean ± σ):  6.43% ±  2.19%
▇█▆▄▂▂▁          ▂▂▁▂▂▁▁▁                                   ▂ …
```

Random nearby agents

---

examples/rabbit_fox_hawk.jl

Found in https://juliadynamics.github.io/Agents.jl/stable/examples/rabbit_fox_hawk/

Fix typo in RFH example

---

docs/src/tutorial.md
src/core/agents.jl
src/core/model.jl

Just fixed a few typos in the documentation

Fix a few typos in the documentation

---

Project.toml
src/Agents.jl
src/simulations/collect.jl

Add progress meter to `run!`

---

src/spaces/openstreetmap.jl

Close #589

---

Project.toml
docs/make.jl
docs/src/api.md
examples/optim.jl
examples/predator_prey.jl
examples/rabbit_fox_hawk.jl
examples/schelling.jl
examples/zombies.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl
src/spaces/openstreetmap.jl
src/submodules/pathfinding/astar.jl

We now need a different example for `GridSpace` and `GridSpaceSingle`. This also gives the opportunity to make an example with different agent types.

New examples for Agents v5.4

---

docs/src/api.md
src/spaces/continuous.jl
src/spaces/utilities.jl
src/submodules/pathfinding/astar_continuous.jl
test/continuous_space_tests.jl
test/grid_space_tests.jl

Generalize `walk!`

---

Project.toml
src/submodules/io/jld2_integration.jl
test/jld2_tests.jl

Fix `GridSpaceSingle` deserialization, add tests

---

examples/celllistmap.jl

After seeing the final rendered page, I think these formatting updates will look better. I really apologize in advance because I don't know how to see the rendered page before it is published, using this system, so I'm not sure, for example, if the `\textrm` LaTeX command will render correctly.

some doc formatting updates

---

examples/schoolyard.jl

Fixes #687

---

.github/workflows/TagBot.yml

Fix TagBot not tagging releases

---

Project.toml
src/core/agents.jl
src/spaces/continuous.jl
src/spaces/graph.jl
src/spaces/grid_general.jl
src/spaces/openstreetmap.jl
test/model_creation_tests.jl

Add docstring support to `@agent`

---

src/core/agents.jl

Closes #729
Let's see if the tests still work because I have no experience with macro programming tbh.

 Simplify three argument macro version

---

src/spaces/grid_single.jl
src/spaces/utilities.jl
test/grid_space_tests.jl

method of `walk!` for `GridSpaceSingle`

---

examples/schelling.jl

#704 updated the return variables, but as #667 points out, the call signature changed. I don't fully understand the syntax, but the solution proposed there worked for me, so I've edited the docs to match here.

Update abmexploration signature

---

CHANGELOG.md
docs/src/api.md
src/spaces/discrete.jl
src/spaces/graph.jl
src/spaces/grid_general.jl

Hi! Amazing library! I created a `npositions` function to address the "todo" in `random_empty`. I'm not so used to Julia style yet (coming from a Python background), hope not to have done any major design mistake :-).
Also don't know if I'm wrong but `positions` function for a `GraphSpace` instance didn't work:
```julia
using Agents, Graphs
g = path_graph(6)
space_graph = GraphSpace(g)
println(positions(space_graph)) # this failed
```
so I updated it, but maybe if this is true, it should be updated in another pr.

Create npositions function

---

benchmark/schedulers.jl

Before this PR, the benchmark got a misleading result: `fastest` benchmark was always `20 ns` since no iteration was made with the scheduler, it also returned results in a strange format, and it didn't work as it was since `SUITE` was undefined. Note that to make it work we need to do something in the `step!` since otherwise the compiler tricks the benchmark returning always `20 ns` so I incremented an attribute.
Before simple printing returned:
```julia
13-element BenchmarkTools.BenchmarkGroup:
tags: ["Schedulers"]
"large_model" => 11-element BenchmarkTools.BenchmarkGroup:
tags: ["by_id", "ByID", "randomly", "Randomly"]
"Randomly" => Trial(10.387 ms)
"by_id" => Trial(46.445 ms)
"ByType" => Trial(57.637 ms)
"ByProperty" => Trial(82.430 ms)
"fastest" => Trial(20.000 ns) # wrong/not …
```

improve benchmark of schedulers

---

CHANGELOG.md
src/spaces/grid_general.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl
test/grid_space_tests.jl

This would solve #750, but it's still a bit clumsy, to improve the design we should change the keys type of `offsets_within_radius` from `float64` to `int` and accept an `int` instead of a `real` in `calculate_offsets`, is this fine?

Solve caching problems in offsets_within_radius

---

src/spaces/grid_single.jl
test/grid_space_tests.jl

FIx #757 but don't know if something else can be considered better than this, but I don't think so, and if the error message is a good one :D

Check if position is already occupied

---

CHANGELOG.md
src/simulations/sample.jl

Seen that the implementation of add_newids! was improvable since some operations can be substitute with much better one, this is the code I used for the benchmark:
<details> <summary> code </summary>
```julia
using Agents, BenchmarkTools
using Agents: sample!, sample2!
mutable struct FakeAgent <: AbstractAgent
id::Int
end
function fake_model(; nagents, scheduler)
model = StandardABM(FakeAgent; scheduler)
for i in 1:nagents
add_agent!(model)
end
model
end
model = fake_model(; nagents = 1000, scheduler=Schedulers.fastest)
@benchmark sample!($model, 100000)
@benchmark sample2!($model, 100000)
@benchmark sample!($model, 10000)
@benchmark sample2!($model, 10000)
@benchmark sample!($model, 1000)
@benchmark sample2!($model, 1000)
@benchmark sample2!($model, 100)
@benchmark sample!($model, 100) …
```

Improve performance of sample! function

---

src/spaces/walk.jl

Pull request regarding issue #754

Set default value of `r` to `r=1` for `randomwalk!`

---

src/spaces/discrete.jl
test/grid_space_tests.jl

Fix bug in `agents_in_position` + tests

---

CHANGELOG.md
docs/src/api.md
src/spaces/discrete.jl
test/grid_space_tests.jl

Add `empty_nearby_positions` + tests

---

src/core/space_interaction_API.jl

Simplified the code eliminating the repetition of the reservoir sampling function in the two methods

simplify code creating resorvoir sampling function

---

CHANGELOG.md
Project.toml
docs/src/api.md
examples/schelling.jl
src/Agents.jl
src/core/model_abstract.jl
src/core/model_concrete.jl
src/deprecations.jl
test/api_tests.jl
test/performance/get_random_agent.jl

Deprecated FixedMassABM

---

src/models/flocking.jl
src/models/schelling.jl
test/csv_tests.jl
test/jld2_tests.jl
test/runtests.jl

Models in this folder aren't still using `UnkillableABM`, but changing this would create conflicts with #766, but they should be really easy to solve anyway. Or we can even wait to change this after #766 is merged.

Use UnkillableABM for some models in the model folder

---

.github/workflows/ci.yml
docs/src/comparison.md

Updated the comparison table with the timing calculated with the script described in https://github.com/JuliaDynamics/ABM_Framework_Comparisons/pull/16. I want to build the docs before merging to see if the visualization is still ok, and I will merge after checking :-)

update comparison with all latest version of the frameworks

---

src/core/model_abstract.jl
src/core/space_interaction_API.jl
test/performance/get_random_agent.jl

A small improvement in execution time
```julia
julia> f(x) = false
f (generic function with 1 method)
julia> @benchmark random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model()) #new
BenchmarkTools.Trial: 387 samples with 1 evaluation.
Range (min … max):  305.611 μs …   4.827 ms  ┊ GC (min … max): 0.00% … 91.75%
Time  (median):     332.832 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   350.827 μs ± 229.440 μs  ┊ GC (mean ± σ):  3.26% ±  4.66%
julia> @benchmark random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model()) #current
BenchmarkTools.Trial: 382 samples with 1 evaluation.
Range (min … max):  346.306 μs …   4.814 ms  ┊ GC (min … max): 0.00% … 90.59%
Time  (median):     413.123 μs               ┊ GC (median):    0.00%
Time  (mean ± σ): …
```

Small improvement in sampling_with_condition_single function

---

CHANGELOG.md
src/spaces/grid_single.jl
src/spaces/walk.jl
test/continuous_space_tests.jl
test/grid_space_tests.jl

To address #799 it is sufficient to change the specific version for `GridSpaceSingle` to the one discussed in the issue, in the meantime I also cleaned a bit the docstring

Extend and improve `randomwalk!`

---

src/spaces/continuous.jl

This should fix the failing of CI, and also fix #733. But I'm not completely sure it is the correct fix, review with care :-)

Fix `true_pairs!`

---

CHANGELOG.md
Project.toml
src/core/model_concrete.jl
src/simulations/ensemblerun.jl
src/spaces/discrete.jl
src/spaces/graph.jl
src/spaces/grid_general.jl
src/spaces/nothing.jl
src/spaces/openstreetmap.jl

In #821 I didn't apply this technique in all places where could be useful, so I'm doing it here :-)
(Anyway given that now adding agents has the same performance in this shorter form we can use it in the ABM_Comparison when we release a new version)

Declare arguments with Vararg

---

docs/src/index.md

Our old statement was incorrect and even confused people into thinking that Agents.jl doesn't care about performance: https://discourse.julialang.org/t/ann-vahana-jl-framework-for-large-scale-agent-based-models/102024/1 
So I rephrased things accordingly

Update comment on design philosophy

---

src/spaces/grid_multi.jl

This is faster and cleaner than before, did some local benchmarks (both micro and macro) to say so

Faster nearby_ids for GridSpace

---

src/spaces/continuous.jl
test/continuous_space_tests.jl

This should fix the bug described in #853.
Maybe it is good if we put the code in the issue with which this was found inside a test. 
@mastrof can you please confirm that this solves the problem with your code?

Fix bug in pos2cell

---

CHANGELOG.md
benchmark/sample.jl
src/Agents.jl
src/simulations/sample.jl
test/randomness_tests.jl

This is up to 2x faster than before because it avoids to use `DataStructures.counter` which in turn use a dict to do the operations

Faster sample! function

---

src/deprecations.jl
src/spaces/nothing.jl

deprecate nothing version of add_agent!

---

src/spaces/grid_general.jl
test/grid_space_tests.jl

This fixes #566. 
Need tests and the implementation should be simplified.

Fix wraparound behaviour when r is big

---

examples/celllistmap.jl
examples/diffeq.jl
examples/flock.jl
examples/measurements.jl
examples/predator_prey.jl
examples/rabbit_fox_hawk.jl
examples/schelling.jl
examples/schoolyard.jl
examples/sir.jl
src/models/flocking.jl
src/models/zombies.jl

Update examples to v6.0

---

docs/logo/example_zoo.jl
examples/schelling.jl
src/Agents.jl
src/core/model_abstract.jl
src/core/model_free_extensions.jl
src/core/model_standard.jl
src/deprecations.jl
src/models/flocking.jl
src/models/schelling.jl
src/submodules/io/jld2_integration.jl
src/submodules/schedulers.jl
test/api_tests.jl
test/jld2_tests.jl
test/model_access_tests.jl
test/performance/get_random_agent.jl
test/runtests.jl

First commit prove that everything still works with UnremovableABM deprecated.
So in subsequent commit I will just update everything outside source
Solves #918

deprecate UnremovableABM

---

src/core/agents.jl
src/core/space_interaction_API.jl
src/spaces/nothing.jl
test/api_tests.jl
test/runtests.jl

Fix add_agent! with all default arguments

---

docs/src/tutorial.md
examples/rabbit_fox_hawk.jl
src/core/agents.jl
test/api_tests.jl
test/performance/branching_faster_than_dispatch.jl
test/performance/variable_agent_types_simple_dynamics.jl

Locally tested, everything works

Change agent in subagent inside multiagent

---

src/spaces/grid_multi.jl

just for fun I tried to make it a bit faster, 5% of flocking model time is spared with this change, not really much :D

Make nearby_ids iterator slightly faster

---

docs/src/tutorial.jl

note on redefining agents

---

CHANGELOG.md
README.md
docs/src/index.md
docs/src/performance_tips.md
src/Agents.jl

Update news for v6

---

docs/src/devdocs.md
src/core/model_abstract.jl

Dev Docs for new models

---

ext/AgentsVisualizations/src/spaces/abstract.jl
src/simulations/sample.jl

This is needed to make everything work in https://github.com/JuliaDynamics/AgentsExampleZoo.jl/pull/27

Fix scatter bug in Visualization extension

---

docs/src/index.md

Lets keep things clean in the homepage

shorten news in index.md

---

Project.toml
examples/event_rock_paper_scissors.jl

Add heading to RPS example

---

README.md

Ref https://github.com/JuliaDynamics/Agents.jl/pull/1027

 Replace monthly download count badge with total downloads badge

---

docs/src/api.md

Add reference to AgentEvent

---

CHANGELOG.md
docs/src/api.md
src/deprecations.jl
src/spaces/continuous.jl
test/continuous_space_tests.jl

Deprecate nearby_ids_exact in favour of nearby_ids with a search keyword

---

Project.toml

yes, sorry I hoped to release in 6.0.14 because it wasn't release until 1 min ago but I didn't make it on time

Bump to 6.0.15

---

Project.toml
test/performance/multiagent_vs_union.jl
test/performance/variable_agent_types_simple_dynamics.jl

This gives a bit of speed-up of multiagent benchmark while not damaging the perf of Union

Speed-up a bit multiagent benchmark against union

---

Project.toml
docs/src/tutorial.jl
docs/src/tutorial.md

Fix broken link in tutorial

---

docs/src/devdocs.md

docs: update devdocs.md

---

Project.toml
examples/delaunay.jl

I messed up the copy paste here...

Fix link to video in Delaunay example

---

Project.toml

Update to 6.2.1

---

docs/src/tutorial.jl

correct minor typos

---

examples/celllistmap.jl

Animation in CellListMap example has title cutoff

---

examples/flock.jl

The flocking example implementation had a very slow and inefficient code. I changed the code adapting it from [here](https://github.com/JuliaDynamics/ABMFrameworksComparison/blob/main/Flocking/Agents/Flocking.jl).

Improve code for flocking example

---

Project.toml
examples/schoolyard.jl
examples/sir.jl
src/spaces/graph.jl

highlight more prominently that GraphSpace != social network

---

src/spaces/grid_general.jl
src/spaces/grid_single.jl

Similar to before, this gets Schelling 1.5x faster

Improve performance of nearby_ids for GridSpaceSingle
