CONTRIBUTING.md

In CONTRIBUTING.md, described how to build the documentation locally using the provided make.jl.

Added a paragraph about building the docs locally.

---

docs/src/schelling.md
examples/schelling.jl

Refactored examples/schelling.jl and replaced code in docs/src/schelling.md with refactored code from examples/schelling.jl. 
In examples/schelling.jl, added descriptive comments and docstrings. Removed tabs. Changed variable names to descriptive variable names, especially in `agent_step!`. Broke up long lines in some cases. 
After refactoring examples/schelling.jl, copied code snippets from examples/schelling.jl to docs/src/schelling.md. Made some minor changes to the comments so that the code snippets make sense while reading the md file.

Refactored examples/schelling.jl and replaced code snippets in schelling.md

---

docs/src/boltzmann_example01.md
examples/boltzmann_wealth_distribution_with_grid.jl

Made substantial edits to the Boltzmann wealth distribution example. The
general train of thought wasn't changed in the .md file, but many
paragraph were restructured significantly and a few paragraphs were
added.
Also, the corresponding files in `examples/` were edited as well. Since
the docs page gives two examples of the Boltzmann model (with a grid and
without), two separate `.jl` files where created so that either
variation can be easily executed by the user. The code referenced in
docs page is exactly the same code in the two `.jl` files.

Refactored Boltzmann example docs and scripts.

---

docs/src/tutorial.md
examples/forest_fire.jl
src/core/agent_space_interaction.jl
src/core/model.jl
src/core/space.jl
src/simulations/data_collector.jl
test/benchmark/benchmark.jl
test/forest_fire_defs.jl
test/schelling_defs.jl
test/schelling_test.jl
test/space_test.jl
test/try_new_api.jl

This PR stores agents in a dictionary `id=>agent` instead of an array. It has biggest impact on the `id2agent` function, which is commonly used in agent-space interactions. Other operations are also slightly faster now.

Change type of model.agents to Dict

---

src/core/model.jl
src/core/space.jl

Now we have:
```
julia> schelling
AgentBasedModel with 0 agents of type SchellingAgent
space: GridSpace with 100 nodes
scheduler: as_added
properties: Dict(:min_to_be_happy=>3)
julia> schelling.space
GridSpace with 100 nodes and 342 edges
```
Closes #55

add pretty printing for abm and space

---

CHANGELOG.md
Project.toml
docs/src/api.md
docs/src/tutorial.md
src/CA1D.jl
src/CA2D.jl
src/core/model.jl
test/api_tests.jl

I have changed `as_added`, to `by_id`, because "as added" is a misleading name. Dictionary keys have no sequence and also no memory of which is added first.
I've added scheduler `fastest` and made it the default, which is just the key iterator of the dictionary.
Added basic API tests for schedulers.

Add a scheduler API and improve scheduler documentation

---

.travis.yml
README.md

For increasing test coverage (https://github.com/JuliaDynamics/Agents.jl/issues/72), seeing where to increase coverage would be nice.
Same setup as eg. [ODE.jl](https://github.com/JuliaDiffEq/ODE.jl/blob/master/.travis.yml#L27).
This would need an admin to connect the repo to [Codecov](https://codecov.io/).

Add Codecov upload to .travis.yml

---

Project.toml
src/simulations/sample.jl
test/api_tests.jl

This adds unit tests for the `genocide!` functions in the API, and implements the requested additional `genocide!(model::ABM, f::Function)`, which closes #134.
I've attempted to keep to the style of similar methods and tests as much as practicable.
For the moment we just throw a `TypeError` if `f` doesn't return `Bool`. Fairly certain that's OK based on other unit tests in the project, but could be easily changed.

Implement and test genocide!(model::ABM, f::Function)

---

src/CA1D.jl
src/CA2D.jl
src/core/model.jl
test/api_tests.jl
test/interaction_tests.jl

Closes #147. Full test of requirements for `AbstractAgent` inside the constructor of `AgentBasedModel`.

Add agent guards to ABM constructor

---

examples/HK.jl
examples/continuous_space.jl
src/core/model.jl
test/api_tests.jl
test/benchmark/mesa/forest_fire.jl

Fixes to the `ABM` constructor following from #159 and subsequent discussions.
- New `AgentBasedModel(agent::A ...) where {A<:AbstractAgent}` constructor
- Updated documentation
- More verbose and helpful errors when `agent` is not instantiated according to our requirements
- Examples and benchmarks are now up to date and functioning in accordance with these changes. Closes #174.

Type Stability & better constructors

---

docs/src/api.md
src/CA2D.jl
src/core/agent_space_interaction.jl
src/core/space.jl
src/simulations/sample.jl
test/api_tests.jl
test/benchmark/mesa/forest_fire.jl
test/interaction_tests.jl
test/runtests.jl
test/space_test.jl

Here's some work connected to #148. There was a lot of different discussions there, and some have already been fixed via the `Space` depreciation and #159.
This PR drops the public facing `coord2vertex` and `vertex2coord` function and replaces their use in example cases where needed. 
One place where this hasn't been done explicitly is `src/CA2D.jl`, which is going to be dropped in #128 anyhow.
Doesn't seem like this simplifies all that much, so would be good to get some feedback on what additional things could be done here.

Remove coord/vertex from API

---

CHANGELOG.md
examples/HK.jl
examples/forest_fire.jl
examples/schelling.jl
examples/sir.jl
examples/social_distancing.jl
examples/wealth_distribution.jl
src/core/agent_space_interaction.jl
src/core/continuous_space.jl
src/core/model.jl
src/core/space.jl
test/api_tests.jl
test/benchmark/DynamicGrids/agents.jl
test/benchmark/benchmark.jl
test/benchmark/mesa/forest_fire.jl
test/collisions_tests.jl
test/interaction_tests.jl
test/model_access.jl
test/runtests.jl

This PR introduces two syntaxes that I find much beetter than what we have now:
1. `model[id]` gives the agent with `id`, i.e. it is `model.agents[id]`.
2. `model.property` gives the entry of `model.properties`. For example, `model.β` gives `model.properties[:β]`.
Motivation: I was extremely displeased about how super verbose it is to get model properties. I was also displeased that getting the agent with `id` is so complicated, given that the dictionary is central and should be more easy to do that. 
This PR resolves everything. It deprecates the function `id2agent` which is useless now.
Closes #166 .

Two convenience syntaxes for getting model propertries and agents

---

src/core/model.jl
test/api_tests.jl

Enables us to set properties in the model with our new extension, and bars all other overrides.
Usecase:
```julia
function model_step!(model)
model.tick += 1
end
model = ABM(AgentX, GridSpace((10,10)); properties=Dict(:tick => 0))
add_agent(model)
step!(model, dummy_step, model_step!, 5)
@assert(model.tick == 5)
```
Nothing else is possible.
```julia
julia> model.space = ContinuousSpace(2)
ERROR: Cannot set space in this manner. Please use the `AgentBasedModel` constructor.
julia> model.agents = Agent1(1, (5,2))
ERROR: Cannot set agents in this manner. Please use the `AgentBasedModel` constructor.
```

Extend setproperty!

---

docs/src/api.md
docs/src/tutorial.md
src/core/model.jl
src/core/space.jl
src/simulations/step.jl
test/api_tests.jl

Great work on #182 - it all looks amazing! Sorry I've been AFK all weekend.
Since there's been a lot of churn and I didn't get the change to do a proper review, I've gone through the final version and think it's solid.
I went through the docs and made sure all exported functions are now represented, as well as if we have any dangling exports. The only method we don't account for in the API docs currently is `dummystep`.
Also, the `Base` extensions could be considered as documentation, although I'm guessing it's not that important to have them explicitly discussed if we use the `model.x` and `model[id]` forms throughout.
If however, it makes sense to be a little verbose in the docs, I've added some words to that effect here. An exception to that is `setindex!` in accordance with 5f5b244. …

Additional documentation

---

CHANGELOG.md
docs/src/api.md
src/core/agent_space_interaction.jl
src/core/continuous_space.jl

This PR changes `biggest_id` to `next_id` because all uses of `biggest_id` add 1 to the largest id to obtain the next id. This is also useful when creating models with heterogeneous agents because the ids need to be managed by the user when new agents are added dynamically throughout the model run.

Change biggest_id to next_id

---

src/core/continuous_space.jl
src/core/space.jl
test/continuousSpace_tests.jl
test/space_test.jl

Closes #153.
Full test suite for the current implementation of node and space neighbors.
There are still some todo's around the continuous space implementation it seems, so we may need to revisit this soon, but the changes here fix all the edge cases for the default metric.

Test suite for node and space neighbors

---

CHANGELOG.md
src/core/space.jl
test/space_test.jl

Closes #124.
Using the `neighbor_type` keyword now allows the user to fine tune their neighbor lookups on directed graphs.

Extend node_neigbors for use with directed graphs

---

src/core/continuous_space.jl
test/collisions_tests.jl
test/continuousSpace_tests.jl

WIP for discussions around #220.
This implements the *all neighbors* scenario at the moment, with a currently unimplemented *true neighbors* to come soon. 
Current benchmarks using test case:
```julia
julia> @btime interacting_pairs(model, 2.0).pairs
5.489 μs (73 allocations: 3.41 KiB)
2-element Array{Tuple{Int64,Int64},1}:
(6, 5)
(4, 3)
julia> @btime interacting_pairs(model, 2.0; method = :all).pairs
10.959 μs (137 allocations: 6.47 KiB)
5-element Array{Tuple{Int64,Int64},1}:
(3, 4)
(4, 5)
(4, 6)
(3, 5)
(5, 6)
```

Extend interacting pairs

---

examples/social_distancing.jl

In an attempt to load the social distancing example a little faster, the framerates have been dropped here to 25fps over the same run schedule, stepping the model twice for each frame.
```
1.4M Apr 23 16:30 socialdist1.gif
1.5M Apr 23 16:30 socialdist2.gif
393K Apr 23 16:30 socialdist3.gif
2.6M Apr 23 16:30 socialdist4.gif
6.5M Apr 23 16:31 socialdist5.gif
```
File sizes are cut in half (current socialdist5.gif is 12.14MB). Animations are not as butter smooth, but are only really visibly different in a side-by-side comparison to most people.
We discussed also dropping the resolution down, but I'm not sure if that's needed. Once the docs build we can test the load time.

Drop framerate for social distancing

---

src/core/agent_space_interaction.jl
src/simulations/sample.jl

Ali alerted me to a bug I introduced in sample! due to how a `Nothing` space is handled. We do need the `add_agent_pos!` method for this space type.

Correct handling of no space in sample

---

CHANGELOG.md
docs/src/api.md
src/Agents.jl
src/core/model.jl
src/core/schedule.jl
test/api_tests.jl
test/runtests.jl
test/scheduler_tests.jl

Improve support for mixed models.
- Adds a `by_type` method (as discussed in #235)
- As a result, schedulers have been moved to their own file
- A method to capture types in a `Union` `union_types`
- We now iterate over subtypes of the union and provide warnings/errors for each.
We can bikeshed naming the scheduler functions, there's probably better ones to use.

Mixed method additions

---

.travis.yml

1c97912e689d2 seemed to kill off codecov, which was using the old way of integrating coverage anyhow. 
From the looks of it, everything is still set up to have it running, it's just disabled currently.

Re-enable codecov

---

docs/src/api.md
examples/predator_prey.jl
examples/sir.jl
examples/social_distancing.jl
src/simulations/collect.jl
test/collect_tests.jl

Closes #234 by swapping `mean(weight)` to `:mean_weight` syntax.

New syntax for aggname

---

test/collect_tests.jl

Fixes #250.
Seems like this change is due to a bit of churn in DataFrames, [this commit](https://github.com/JuliaData/DataFrames.jl/commit/b1f675d89b63e5da4c6bdf0fb3f92bfab0c4d8c0) updates the docs at least concerning the adjustment. `names` will now output strings, although `propertynames` will still output symbols.

Use propertynames instead of names

---

CHANGELOG.md
Project.toml
docs/src/api.md
src/core/continuous_space.jl
test/continuousSpace_tests.jl

Closes #252 by supporting agent pairing separated by agent type in mixed models.
Continuing discussions from #252, whilst this is essentially a simple extension, so too are most of the `interacting_pairs` implementations that are already extant. In addition this change improves our mixed model support, so in general this is a win IMO.

Mixed model support in interacting_pairs

---

examples/schelling.jl

Aggregate is deprecated in favor of 'split-apply-combine' in DataFrames.jl.
(see https://juliadata.github.io/DataFrames.jl/stable/man/split_apply_combine/)

Update schelling.jl (Aggregate is deprecated)

---

src/core/discrete_space.jl

NTuple{Int} is an incorrect type, so I changed the description to something more explanatory.

Clarify NTuple type for GridSpace

---

Project.toml
src/core/continuous_space.jl
test/continuousSpace_tests.jl

Closes #288 
One of our tests actually should have caught this already. :/ I've made an explicit catch based on #288 though just to be sure.

Fix euclidean pair test in continuousspace

---

examples/opinion_spread.jl
examples/predator_prey.jl
src/core/model.jl
src/models/Models.jl
src/models/opinion.jl
src/models/predator_prey.jl
src/models/sugarscape.jl
src/models/wealth_distribution.jl
src/spaces/discrete_space.jl

Recent changes have altered some of the mechanisms we use, that killed off a lot of the functionality in the Models library and broke some examples. This PR fixes that, alongside a few other fixes, like the pre-emptive merge of sugarscape and an omission in the wealth model.

Patch up models and examples

---

CHANGELOG.md
src/core/space_interaction_API.jl
src/spaces/graph.jl

Closes #312 
I've done a number of iterations on this. Whilst it's not the best performing in every situation, it aligns with our output requirements for these functions (iterators, not vectors) and provides the best all round numbers that I can find.
The big discrepancy is that the LightGraphs implementation that returns a vector must be wrapped in an iterator, and that increases the time spent here. Any ideas how to mitigate this? (we could state that graph space returns vectors and grid space iterators, but that's not a clean solution).
(tests have not been updated, that will come once we get an agreed upon implementation)
```julia
model = ABM(Agent5, GraphSpace(path_graph(500)))
for _ in 1:2000 add_agent!(model, rand()) end
a = random_agent(model)
pos = a.pos
```
Baseline
```julia …
```

Graph neighbor improvements (Discussion)

---

CHANGELOG.md
src/spaces/graph.jl
test/graph_tests.jl
test/runtests.jl

Closes #264
I am having trouble because I don't know anything about LightGraphs and perhaps someone should help me here.
How does the order of node integers change in LightGraphs.jl when you add another one or remove one? If I do `rem_vertex!`, can I just do `deleteat!(model.space.s, n)` and then the correspondence between node numbers in the graph, and node numbers in `model.space.s` stays the same? 
And what about adding new nodes? If I add a new node in lightgraphs, is it automatically becoming the `nv(graph)+1` node? From the documentation of `add_vertex!` it looks like it.

Allow mutable graphs

---

CHANGELOG.md
docs/src/api.md
src/spaces/utilities.jl
test/space_test.jl

This is a solution to the discussion around #346.
Users coming from Netlogo will be used to [Turtles](https://ccl.northwestern.edu/netlogo/docs/programming.html#procedures), which have been historically used in a number of other places to represent movement on a grid. 
I've simplified the concept a bit here: rather than having a heading and a direction (which works fine for us right now in `ContinuousSpace`, and doesn't require any extra help from the framework), the `walk!` function moves agents on 2D grids, respecting boundary conditions where necessary. 
This should solve @mbruna's initial question, as well as providing a solution for future netlogo converts.

Walk utility

---

src/spaces/utilities.jl
test/space_test.jl

Closes #352.
Gives us ND grid and continuous walks for both PBC and non-PBC spaces. The `ifempty` keyword will only move an agent to a new position if it is empty (`GridSpace` only).
Two simple random walk helpers are also included. I was considering making these more complex and allowing arbitrary random distributions, but that would make us require Distributions.jl. Don't think it's really needed, since users can extend this method quite easily themselves.

Simplify, and extend walk!

---

CHANGELOG.md
src/core/space_interaction_API.jl
src/spaces/grid.jl
test/space_test.jl

Closes #314 by allowing `r` to be a tuple. We need to store a separate dictionary for this, but in general there is not too much overhead.

Tuple for search direction on GridSpaces

---

examples/daisyworld.jl
examples/daisyworld_matrix.jl
examples/forest_fire.jl
examples/game_of_life_2D_CA.jl
examples/predator_prey.jl
examples/schelling.jl
examples/sir.jl
examples/siroptim.jl
examples/social_distancing.jl
examples/wealth_distribution.jl
src/models/game_of_life.jl
src/simulations/collect.jl
src/spaces/continuous.jl

Hi! I'm working on a linter, and saw that this repository is set to Julia 1.5 and has [26 occurrences](https://lint.huijzer.xyz/github/juliadynamics/agents.jl/#abbreviate_keyword_argument_values_26_hits) of using 
```
f(a, b; c = c)
```
which [from Julia 1.5 onwards](https://julialang.org/blog/2020/08/julia-1.5-highlights) can be abbreviated to
```
f(a, b; c)
```
This PR applies this abbreviation. Feel free to close this PR immediately if you're not interested in this small refactoring.
Note that currently, I'm not matching cases like `f(a, b; c = c, d = e)` or `f(a, b; d = e, c = c)`. If you want to include this in one big PR, then let me know, and I'll add the patterns and update this PR :smile:

Abbreviate keyword argument values

---

CHANGELOG.md
benchmark/agents.jl
examples/daisyworld.jl
examples/daisyworld_matrix.jl
examples/forest_fire.jl
examples/game_of_life_2D_CA.jl
examples/measurements.jl
examples/opinion_spread.jl
examples/predator_prey.jl
examples/schelling.jl
examples/sugarscape.jl
src/models/daisyworld.jl
src/models/forestfire.jl
src/models/game_of_life.jl
src/models/opinion.jl
src/models/predator_prey.jl
src/models/schelling.jl
src/models/sugarscape.jl
src/spaces/discrete.jl
src/spaces/grid.jl
test/api_tests.jl
test/collect_tests.jl
test/runtests.jl
test/space_test.jl

Closes #361
Not changed everywhere, just where appropriate in the examples and models. Internal references are not required to be altered. 
Added in a few places (tutorial and the first example people see: Schelling) a point that `Dims` is just an alias for `NTuple{N,Int}`.

Move gridspace examples to Dim shorthand for their position

---

.github/workflows/TagBot.yml
.github/workflows/doccleanup.yml

Adds a new action that should keep the previews in `gh-branches` a little cleaner than historically. Taken from  CliMA/TimeMachine.jl and Documenter.jl docs.

Preview cleanup action

---

CHANGELOG.md

See https://github.com/JuliaDynamics/Agents.jl/blob/88af0ec548ade7ec5d805b7aa7c85e49dadbb931/src/spaces/grid.jl#L26-L65 for the correct defaults.

Fix typo in GridSpace periodic default

---

.github/workflows/ci.yml

I think we'll have seed failures here, as we did previously in #271, where we 'solved' the issue by dropping 1.0 support. We don't have that luxury this time round.

Enable 1.6rc testing on CI

---

CHANGELOG.md
docs/src/api.md
src/core/model.jl
test/api_tests.jl

A start on #408. These methods handle any order you need / can fit in memory. Initially I thought it would only be required to export the map functions, but in the case of the filtered versions of the map it's not clear which ids correspond to the output.
So, in our examples for these methods, we'll need to state clearly that you can get indexes for your results in a few ways:
- No filter, you just need one row of indices: `by_id(model)`
- No filter, you want the lot: collect the `group_id_iter`. The results are correct for the agent version as well.
- Filter: use the filter to filter the `group_id_iter`. For example: `Iterators.filter(allunique, group_id_iter(2,model))`.
Feel free to suggest better names here. Still needs tests, and the examples we discussed.

High-order iterators and maps

---

Project.toml
docs/src/api.md
docs/src/comparison.md
docs/src/index.md
docs/src/performance.md
docs/src/tutorial.md
src/core/agents.jl
src/core/model.jl

This is an attempt to make the documentation of Agents.jl more welcoming to new users. 
- Remove comparison from homepage
- Add some words about the design of agents in homepage
- Declutter tutorial by removing non-crucial information. (obviously the spaces are crucial information however listing there the docs of all spaces takes a lot of space, and is not necessary at the moment)

New intro docs

---

Project.toml
src/spaces/openstreetmap.jl
test/osm_tests.jl

This closes #427
Starting from the master branch, I've updated the function "travel!" in src/spaces/openstreetmap.jl:
Only the commented part is new, and it is essentially a copy+pasted version of the "park!" function (same file).

fixed bug in src/spaces/openstreetmap.jl's function 'travel'

---

src/spaces/utilities.jl

Fixed typo "opreation" --> "operation" in line 102

Fix typo in utilities.jl

---

docs/src/api.md

Adds a link to the iteration section of the docs in the higher order methods to make things a little clearer.

Link grouped methods to iteration notes

---

examples/forest_fire.jl
src/models/forestfire.jl
test/collect_tests.jl

A more performant forest fire which is more Cellular Automata than Agent, as the current description has it.
v4.0 runtime: 24.3 ms, this version: 1.5 ms

Automata forest

---

Project.toml
src/simulations/collect.jl
test/collect_tests.jl

Very minor fix to #494 by adding type checking of `model.property`. New to Julia so let me know if I missed anything obvious.

Model property type checking in `init_model_dataframe`

---

CHANGELOG.md
Project.toml
docs/src/tutorial.md
src/simulations/collect.jl
test/collect_tests.jl

This is fine:
```julia
(model, agent_step!, model_step!) = Models.schelling()
function assets(model)
happy(model) = model.min_to_be_happy
super_happy(model) = model.min_to_be_happy * 5
return [happy, super_happy]
end
_, data = run!(model, agent_step!, 5; mdata = assets(model))
```
This is not:
```julia
models = some_generator()
_, data = ensemblerun!(models, agent_step!, 5; mdata = assets(model{s}?))
```
New process:
```julia
_, data = run!(model, agent_step!, 5; mdata = assets)
_, data = ensemblerun!(models, agent_step!, 5; mdata = assets)
```
This method **should not** be extended to `adata`. There is no need and drastically complicates the codebase / doc requirements.

Add a generator method for mdata collection

---

.github/workflows/ci.yml
CHANGELOG.md
docs/src/api.md
docs/src/comparison.md
docs/src/index.md
src/Agents.jl
src/deprecations.jl
src/spaces/continuous.jl
src/spaces/utilities.jl
src/submodules/io/jld2_integration.jl
src/submodules/pathfinding/all_pathfinders.jl
src/submodules/pathfinding/astar.jl
src/submodules/pathfinding/astar_continuous.jl
src/submodules/pathfinding/astar_grid.jl
test/astar_tests.jl
test/continuousSpace_tests.jl
test/jld2_tests.jl

None of the new methods are tested, and the docstrings are just copied over from `astar_grid.jl`. ~I'll work on getting `move_along_route!` working for periodic continuous spaces before addressing that~ (done). Some points to address:
- `set_target!` and `set_best_target!` for continuous space require the model to be passed in, for continuous space dimensions
- I chose to keep `find_path` as it is and add a new `find_continuous_path` method. The alternative was having `find_path` return `parent` and each `set_target!` method extract the path from that, possibly through another method such as `unravel_path`.
TODO:

Continuous Space Pathfinding

---

CHANGELOG.md
Project.toml
docs/src/comparison.md
src/spaces/discrete.jl
test/model_access.jl

`random_empty` and kin require a full filter of the board each time they're called regardless of how sparse the agents are populating it. This PR provides us quite a noticeable performance enhancement using guesses, that we stop using once we start failing too much.
The core concept is a loop that gives us a `random_position` and returns it, otherwise tries again.
```julia
while true
pos = random_position(model)
isempty(pos, model) && return pos
end
```
Benchmarking on the maximum time of our current and this proposed solution, we can find the place where we guarantee chance will win out to filtering/collecting.
```julia
function rand_mt(model)
has_empty_positions(model) || return nothing
while true
pos = random_position(model)
if isempty(pos, model)
return pos
end
end
end
julia> …
```

Empty positions performance boost

---

examples/wealth_distribution.jl

In the model with space the code passes `agent_step!` instead of `agent_step_2d!`.

Updating agent_step function

---

examples/zombies.jl
src/models/zombies.jl
src/spaces/openstreetmap.jl
test/osm_tests.jl

Closes #587 
The example also didn't run before because `using Random` wasn't there.

Update `test_map` doc, Fix zombies example

---

docs/src/api.md
examples/zombies.jl
src/deprecations.jl
src/models/zombies.jl
src/spaces/openstreetmap.jl
test/osm_tests.jl

Closes #449 
- `move_along_route!` returns the remaining distance left to move
- Update docstring accordingly
- Update zombies example accordingly

`move_along_route!` change, zombies update

---

Project.toml
examples/zombies.jl

Hello,
according to the zombie outbreak tutorial, OSM.nearest_road and OSM.nearest_node take a position in form of (latitude, longitude).
However, it seems to be the case that they actually take data in form of (longitude, latitude) (see docstrings of the functions as defined in openstreetmap.jl). Consequently, the video which is produced by the tutorial is different from what one would expect from the tutorial code. The zombie starts at the top left corner, while from (51.5328328, 9.9351811) one would expect the zombie to start on the right, if the format was (latitude, longitude).
The reason why I discovered this issue was because I wanted to let a zombie start from my house - I don't think I will be the last one to try this :D.

fix latitude and longitude of first zombie in zombie example

---

src/core/model.jl

I saw `ABM` used in an example, so I checked its docstring, but I had to search the codebase for `const ABM =` to find its docstring. This should expedite that process.

Add docstring to AMB

---

src/core/model.jl

The code changes should be a no-op except for dropping support for the (now unused) two-argument version.
Docstring changes: 
1) The argument must be a type
2) The function returns a tuple, not a set
3) `Union`s don't have order. For example, 
```
julia> Agents.union_types(Union{Grass, Wolf, Sheep})
(Grass, Sheep, Wolf)
julia> Union{Grass, Wolf, Sheep} === Union{Grass, Sheep, Wolf}
true
```

simplify union_types and edit docstring

---

.gitignore
CHANGELOG.md
docs/src/api.md
docs/src/distances_example_plot.jl
examples/flock.jl
src/core/space_interaction_API.jl
src/deprecations.jl
src/models/flocking.jl
src/spaces/continuous.jl
src/spaces/grid.jl
src/spaces/utilities.jl
src/submodules/pathfinding/astar_continuous.jl
test/astar_tests.jl
test/performance/branching_faster_than_dispatch.jl
test/space_test.jl

Closes #632 
I've added some utility functions to calculate manhattan distance between two agent positions. Should work for both periodic/non-periodic. This allows users to easily use the distance metric in their models.
I have not integrated the manhattan distance as a new `metric` for GridSpace. Would that be necessary?
*Sidenote*: We should maybe change the `periodic` keyword to `toroidal` at some point because that word is a bit more common in this context as far as I know.

Add `:manhattan` metric and `manhattan_distance` utility function

---

src/core/space_interaction_API.jl
test/space_test.jl

It's basically just moving a couple lines down to fix the bug where the first element of the iterator never gets picked.

Fix `random_nearby_id`

---

src/submodules/pathfinding/astar_continuous.jl
test/astar_tests.jl

The issue was wrapping in periodic space. The shortest direction from `(0,0)` to `(4.75,4.75)` in a periodic space is `(-0.25,-0.25)`, which is where it tried to move to. Fixed by using the new `Agents.spacesize` function.

Fix astar test

---

src/spaces/continuous.jl
test/continuous_space_tests.jl

fix #675
I also renewed the facing logic to:
```julia
!(dot(r2, v1) > 0 && dot(r1, v2) > 0) && return false
```

Fix elastic collision

---

src/spaces/openstreetmap.jl

Closes #681 
Should we allow the user to tune `search_radius` (third parameter to [nearest_way](https://deloittedigitalapac.github.io/LightOSM.jl/stable/nearest_way/#LightOSM.nearest_way)), potentially causing the method to return `nothing` (and document it, of course)

Use `LightOSM.nearest_way` for `nearest_road`

---

src/simulations/ensemblerun.jl
test/collect_tests.jl

I added a small bug in my PR #624 for updating `ensemblerun!` for improved parallelism and progressbars. My change (reverted here) makes dispatching work incorrectly when `models` is a vector/tuple and `n` is a stopping function. This PR reverts that change so expected behavior is recovered. Sorry for this needless hassle!

Reverted `n` parameter in ensemblerun! to correct pre-5.4.x version

---

examples/predator_prey.jl

In the wolf `walk!`, `ifempty=false` is required for the wolf to eat the sheep. Without `ifempty=false` the wolf would starve to death.

In the wolf `walk!`, parameter update

---

CHANGELOG.md
Project.toml
docs/src/api.md
src/deprecations.jl
src/spaces/graph.jl
test/graph_tests.jl

Hello,
We are the developers of [MultilayerGraphs.jl](https://github.com/JuliaGraphs/MultilayerGraphs.jl). 
We're looking towards publishing a new release that, among other things, integrates our package with Agents.jl. In doing so, we noticed that Agents.jl [implements](https://github.com/JuliaDynamics/Agents.jl/blob/5258c1bceeed41342e3ac36526bf7932b083c9ea/src/spaces/graph.jl#L129) the methods  `add_node!`,`rem_node!` and `add_edge!`.
We propose to rename `add_node!`,`rem_node!` to `add_vertex!`,`rem_vertex!` and have them extend `Graphs.jl`'s homonymous methods, for the following two reasons:
1. They effectively add and remove vertices, so this would help standardize names across ecosystems;
2. Our package needs to distinguish between nodes and vertices, and so `add/rem_node!` is …

Rename add/rem_node! to Graphs.add/rem_vertex!, implement rem_edge!

---

Project.toml
src/spaces/openstreetmap.jl

Default `OSMGraph` constructor functions don't call `LightOSM.create_rtree!`

Fix `nearest_way` not working

---

examples/schelling.jl

Closes #667 
Docs should show `fig, abmobs` instead of `fig, adf, mdf` as it has been in previous version of InteractiveDynamics.

Fix return variables of abmexploration

---

Project.toml
src/core/agents.jl
src/simulations/paramscan.jl
test/collect_tests.jl

This PR addresses https://github.com/JuliaDynamics/Agents.jl/issues/706

removed `::Int` so that `paramscan` take `n::Function`

---

examples/diffeq.jl

I believe the id field in the definition of a NoSpaceAgent is not necessary (and indeed it gives an error when trying to define it explicitly). Removed that, the example runs smoothly.

id::Int field redundant: removed

---

CHANGELOG.md
src/simulations/collect.jl
test/collect_tests.jl

When initializing the `adata` dataframe for multi-agents, code tries to look for the first object instance of the different agent types., so that it can be used to extract the desired property types for dataframe header. 
In the specific case where one agent type doesn't yet exist at model initialization (to be added later on while stepping the simulation), this will cause an error. 
The behavior now is to default the missing agent type's properties to `Missing`. If desired, I can also leverage `hasfield` and `fieldtype` when the desired property is a `Symbol`

Add try-catch to finding first agent instance in multi_agent_types!

---

src/spaces/graph.jl

Looking at the source code I found that `splice!` can be substituted with `deleteat!`, `deleteat!(a, findfirst(x -> x == b, a))` is 1.5x faster than `splice!(a, findfirst(x -> x == b, a))` 
```julia
function splice_test(a::Vector{Int}, b::Int)
s = splice!(a, findfirst(x -> x == b, a))
return nothing
end
function deleteat_test(a::Vector{Int}, b::Int)
s = deleteat!(a, findfirst(x -> x == b, a))
return nothing
end
using BenchmarkTools
s = 1000
with_splice = @benchmarkable (for i in 1:b splice_test(a,i) end) samples=1 evals=1 setup=(a = Int[1:$s;]; b = $s)
with_deleteat = @benchmarkable (for i in 1:b deleteat_test(a,i) end) samples=1 evals=1 setup=(a = Int[1:$s;]; b = $s) 
run(with_splice)
run(with_deleteat)
```
which returns
```julia
BenchmarkTools.Trial: 1 sample with 1 evaluation.
Single …
```

Substitute splice! with deleteat! in remove_agent_from_space for graphs

---

CHANGELOG.md
src/spaces/continuous.jl
src/spaces/grid_general.jl

This (still to be tested and adapted well) solves the memory bug described in https://github.com/JuliaDynamics/Agents.jl/issues/739, the problem was that we saved a float value which means that for a continuous space (with a grid behind it) it will grow and grow over all the simulation, but this can be avoided saving just the floored/ceiled values. The patch can surely be improved a bit in terms of code used.

Solve unbounded cache problem when r is not an integer

---

src/spaces/utilities.jl

I noticed that the metrics code was not standardized: different methods (for loop, element-wise operations, ...) were used. I tried to simplify the code while mantaining/improving performance. Runned this benchmark
<details> <summary> Benchmark </summary>
```julia
using Agents, BenchmarkTools
using Agents: euclidean_distance, manhattan_distance, euclidean_distance2, manhattan_distance2
@agent Ag GridAgent{2} begin end
function model_setup()
multigrid = GridSpace((10, 10), periodic=true)
model = ABM(Ag, multigrid)
return model
end
a, b = (2,3), (5,4)
@btime euclidean_distance($a, $b, model) setup=(model=model_setup())
@btime manhattan_distance($a, $b, model) setup=(model=model_setup())
@btime euclidean_distance2($a, $b, model) setup=(model=model_setup())
@btime manhattan_distance2($a, $b, …
```

stardardize metric functions

---

CHANGELOG.md
src/spaces/utilities.jl

Saw that there was some huge room for improvement for the algorithm used in this particular function so I tried to come up with something better:
<details> <summary> Correctness verification + benchmark code </summary>
```julia
using Agents, BenchmarkTools, Random
using Agents: get_direction, get_direction2
@agent Ag GridAgent{2} begin end
function model_setup()
multigrid = GridSpace((10, 10), periodic=true)
model = ABM(Ag, multigrid)
return model
end
function model_setup2()
multigrid = GridSpace((10, 10, 10), periodic=true)
model = ABM(Ag, multigrid)
return model
end
model = model_setup()
for _ in 1:10000
a, b = (rand()*10, rand()*10), (rand()*10, rand()*10)
@assert get_direction(a, b, model) == get_direction2(a, b, model)
end
a, b = (2.0, 3.7), (5.8, 4.7)
@benchmark get_direction($a, …
```

Improve performance of get_direction function

---

CHANGELOG.md
src/spaces/utilities.jl

Tried to come up with something better for this particular function, this new function gives some big speed-up:
<details> <summary> Benchmark </summary>
```julia
using Agents, Graphs, BenchmarkTools
using Agents: nearby_positions, nearby_positions2
graph_1 = GraphSpace(cycle_graph(200))
graph_2 = GraphSpace(erdos_renyi(500, 0.3))
mutable struct a <: AbstractAgent
id::Int
pos::Int
end
model_1 = ABM(a, graph_1)
model_2 = ABM(a, graph_2)
@btime nearby_positions(1, $model_1, 1)
@btime nearby_positions(1, $model_2, 1)
@btime nearby_positions2(1, $model_1, 1)
@btime nearby_positions2(1, $model_2, 1)
@btime nearby_positions(1, $model_1, 2)
@btime nearby_positions(1, $model_2, 2)
@btime nearby_positions2(1, $model_1, 2)
@btime nearby_positions2(1, $model_2, 2)
@btime nearby_positions(1, $model_1, …
```

Improve performance of nearby_positions for graphspace

---

CHANGELOG.md
src/spaces/utilities.jl

this is mostly a refactor where I added a dispatch to space instead to pass directly the model to some utilities function, but there is also an improvement in performance for normalize_position in the non periodic grid case, I calculated that this new function is 50x faster than the previous one since calling `ones(Int, D)` is avoided now!

Refactor some utilities functions

---

src/core/model_concrete.jl
src/simulations/step.jl

The presence of the id can be spared to be checked when using an UnremovableABM. I also had to change the definition of the aliases in `model_concrete.jl` because previously referring to different ABM implementation wasn't possible, but I'm not sure if this is the right way to do it even if it works. Consider also that for an UnremovableABM checking if an id is present is much more costly than for a StandardABM since the vector has to be scanned.

Not check presence of id for UnremovableABM models in step!

---

src/simulations/collect.jl
src/submodules/io/jld2_integration.jl

This solves #773 since now the serialization includes the type of the agents_container so that we can reinstantiate the model with the correct container in `from_serializable`, it should now be possible to use it with all models implementations

Make model serialization more general

---

CHANGELOG.md
Project.toml
src/spaces/grid_multi.jl

Found some little optimizations for the iterator, running some benchmark it is more or less 2x faster to iterate over results now!
<details>
```julia
using Agents, BenchmarkTools
@agent A GridAgent{2} begin
end
function periodic_model(; numagents = 1000, griddims = (20, 20))
space = GridSpace(griddims, periodic = true)
model = ABM(A, space)
for _ in 1:numagents
add_agent!(A, model)
end
return model
end
function aperiodic_model(; numagents = 1000, griddims = (20, 20))
space = GridSpace(griddims, periodic = false)
model = ABM(A, space)
for _ in 1:numagents
add_agent!(A, model)
end
return model
end
@benchmark collect(nearby_ids($(10,10), model, 1)) setup=(model=periodic_model())
@benchmark collect(nearby_ids($(10,10), model, 1)) setup=(model=aperiodic_model())
@benchmark …
```

Improve the speed of GridSpaceIdIterator

---

CHANGELOG.md
Project.toml
src/spaces/grid_general.jl
test/grid_space_tests.jl

This functions are faster and faster than using a reservoir sampling technique, since this way the operations are O(1), benchmark code used 
<details> 
```julia
using Agents, BenchmarkTools
@agent A GridAgent{2} begin
end
function aperiodic_model(; griddims = (100, 100))
space = GridSpaceSingle(griddims, periodic = false)
model = ABM(A, space)
return model
end
function periodic_model(; griddims = (100, 100))
space = GridSpaceSingle(griddims, periodic = true)
model = ABM(A, space)
return model
end
@benchmark random_nearby_position($(1,1), model, 10) setup=(model=periodic_model())
@benchmark random_nearby_position($(50,50), model, 10) setup=(model=periodic_model())
@benchmark random_nearby_position($(1,1), model, 1) setup=(model=aperiodic_model())
@benchmark random_nearby_position($(50,50), …
```

Faster random_nearby_position for GridSpaces

---

docs/src/comparison.md
src/spaces/continuous.jl

Some little improvements to the methods, maybe most notably the test if the pos is inside the space in `move_agent` now tests also the lower bound as it was supposed to do.
edit: also changed netlogo version which I incorrectly reported as 6.4 but the lastest one, which I used to run the benchmark, it's actually the 6.3.0 :Q

Some small improvements to continuous space methods

---

CHANGELOG.md
Project.toml
src/core/space_interaction_API.jl

This is a bit faster than before, something like 2x faster, this is for a r=10 on a grid using the same benchmark as the one in in #784 (even if the sampling method was changed in #784 for a better method I used the old one which used the function):
before:
```julia
Range (min … max):  4.288 μs …   8.639 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     4.467 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   4.497 μs ± 131.984 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%
▅▄█▇▇▇▄▅▂                                       
▁▁▁▁▁▁▂▂▂▄▅▇████████████▆▅▄▅▄▃▄▄▄▄▃▄▃▃▃▂▂▂▂▂▂▁▁▁▂▁▁▁▁▁▁▁▁▁▁ ▃
4.29 μs         Histogram: frequency by time        4.84 μs <
```
now:
```julia
Range (min … max):  2.096 μs …   6.704 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     2.228 μs               ┊ GC …
```

Faster resorvoir_sampling_single function

---

examples/sir.jl

In sir.jl example, ```sample()``` and ```Weights()``` functions were used without ```using StatsBase```.

Add using StatsBase to sir.jl example

---

CHANGELOG.md
Project.toml
src/core/model_abstract.jl
src/core/space_interaction_API.jl
test/grid_space_tests.jl

This implements the filtering feature discussed in #650, in the process I created two new function `sampling_with_condition_single` and `sampling_with_condition_agents_single` so that to reuse the code. Some benchmarks using the code posted in #650 seem good:
```julia
julia> @btime random_nearby_id($(25,25), model, 10) setup=(model=periodic_model())
171.405 μs (17884 allocations: 845.36 KiB)
54290
julia> f(x, y) = true
f (generic function with 1 method)
julia> @btime random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model())
242.911 μs (17893 allocations: 1.14 MiB)
66712
julia> f(x, y) = false
f (generic function with 1 method)
julia> @btime random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model())
354.953 μs (17893 allocations: 1.14 MiB)
```
But this PR still …

Filtering for random_nearby_*

---

CHANGELOG.md
src/submodules/schedulers.jl

I refactored some operations:
- Added a faster `get_ids!` function in the case of a `UnremovableABM`
- Changed the ByID for an `UnremovableABM` in the simple call of the id container, now it is much faster and equivalent to the fastest scheduler
- `ByProperty` now can accept any properties values, not just floats, but it reallocates each time the vector `properties`, it seems like reallocating is better since doing this 
```julia
if isempty(sched.properties)
sched.properties = [Agents.get_data(model[id], sched.p) for id in sched.ids]
else
resize!(sched.properties, length(sched.ids))
for (i, id) in enumerate(sched.ids)
sched.properties[i] = Agents.get_data(model[id], sched.p)
end
end
```
instead of  `sched.properties = [Agents.get_data(model[id], sched.p) for id in sched.ids]`
makes the …

Refactor of some scheduler operations

---

src/spaces/walk.jl

This makes `walk!` a little bit more performant (something like 5%), there was no specification for return values in the docs so I think it should be fine to return the `agent`

Fix small return type instability in `walk!`

---

src/spaces/utilities.jl

there was a huge mistake in `manhattan_distance` :O Probably my fault, sorry (new patch version/minor version?)
Also took the opportunity to make `get_direction` more performant, this is 2x faster
(failed test is the one solved in #805)

Fix `manhattan_distance`

---

CHANGELOG.md
src/spaces/grid_general.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl

This came to my mind today, it's a simple change but has a big impact: 
Flocking in the large version is 1.5x faster now! edit: but with a big catch :D, see below
In general it has a good impact when periodic is true and just a slight impact when it is false.
It's time for 5.15 I guess  :D

Improve speed of Nearby Look-ups in GridSpaces

---

src/core/space_interaction_API.jl

Now I don't see any regression with these changes, running the benchmark in the related issue #820 
```julia
julia> @benchmark model_1()
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):  125.087 μs …   2.810 ms  ┊ GC (min … max):  0.00% … 90.66%
Time  (median):     134.490 μs               ┊ GC (median):     0.00%
Time  (mean ± σ):   158.740 μs ± 207.101 μs  ┊ GC (mean ± σ):  12.16% ±  8.70%
▁▆███▇▆▅▄▄▃▃▂▂▂▁▁▁▁▁▁▁  ▁▁                                    ▃
██████████████████████████▇█▇▆██▇▆▆▇▇▇▆▆▅▅▅▁▅▅▃▅▄▅▄▄▃▅▄▄▅▃▃▁▃ █
125 μs        Histogram: log(frequency) by time        257 μs <
Memory estimate: 434.19 KiB, allocs estimate: 4385.
julia> @benchmark model_2()
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):  114.889 μs …   2.980 ms  ┊ GC …
```

Fix performance of some versions of add_agent

---

CHANGELOG.md
Project.toml
src/simulations/sample.jl
test/api_tests.jl

Implemented the function described in #809. 
I decided to include it in the sample.jl file since this redefinition of `deepcopy` should benefit also `sample!`.
This still needs some tests. Will also benchmark the benefit for `sample!`.

New function: replicate!

---

Project.toml
docs/src/api.md
src/simulations/sample.jl

This is more correct since:
- in both the functions now the agent is created without changing the immutable `id` field, I also verified that now the `id` field is never updated throughout the library which means that we could declare it constant in the internal macros if we want to do so
- secondly it deepcopies also the argument given in kwargs, this could be useful to prevent bugs from the user side
- the replicate! function is exported :D 
I also verified that this doesn't change the performance of the functions, actually it improves the case where kwargs are given since it doesn't re-set the fields after the agent is created

More correct replicate! (and sample!)

---

test/randomness_tests.jl

The test `mean_weights_new > mean_weights` sometimes throws errors since the model was not seeded e.g. https://github.com/JuliaDynamics/Agents.jl/actions/runs/5598262478/jobs/10237678720?pr=831 , now it should be fixed

Fix test throwing error

---

CHANGELOG.md
src/core/agents.jl
test/model_creation_tests.jl
test/runtests.jl

This tries to split in two parts #831 since the part with the consts variable is more hacky, but using default values is very easy and we can support it almost with no changes

Allow using default values in agents macro

---

docs/src/index.md

Recently we had a few questions and issues pop up on Slack which were due to people using older versions (often v4.x) of Agents.jl.
This PR adds a short tip box to the "Getting started" section in the docs and advises to generally use the latest released version of Agents.jl.

Add tip box to getting started section

---

CHANGELOG.md
docs/src/api.md
src/core/model_abstract.jl
src/core/space_interaction_API.jl
src/spaces/discrete.jl
src/spaces/graph.jl
test/grid_space_tests.jl
test/randomness_tests.jl

These are the functions we need for WolfSheep in the benchmark repo. And they are also useful in general.
There is also another important change in this PR -> a new keyword `alloc` for all the filtered random searches: this makes it possible to choose between the best method for each case:
- allocation + evaluation of the filtering on just some members
- no allocation + evaluation of the filtering on all members
Notice that alloc is currently set to False (even if some benchmarks are needed to say if it is better to set it so), which means that the new methodology is currently being tested
This is still a rough PR, many things are a bit redundant or can be improved, docstrings are lacking, etc...

New functions: random_id_in_position & random_agent_in_position

---

src/core/agents.jl

this should solve #725 , can you @mastrof say to me if this is what you intended and that it works for your use case please?
Now this works:
```julia
using Agents
abstract type AbstractFoo{D} <: AbstractAgent where D end
@agent MyFoo2{D} ContinuousAgent{D} where D AbstractFoo{D} begin; end
```

Agents macro allows parametric types and subtyping

---

src/simulations/sample.jl

It is actually possible to specify a new position in `replicate!`, this should be documented, also simplified a bit the function

Document replicate! less restrictively

---

src/Agents.jl
src/core/model_concrete.jl
test/model_creation_tests.jl

Closes #855.
I added an extra check to the `do_checks` function to allow the creation of models with calls of the form `ABM(ContinuousAgent{D}, ContinuousSpace((1,1))` for backward compatibility, even though this now results in model being not concretely typed.
This change is also mentioned in the welcome message and in the warning for agents with non-concrete types.
I used a regex for the check instead of subtyping because I did not find another easy way to *only* get the case where `ContinuousAgent{D}` is used with a Float64 space.

Fix model creation with ContinuousAgent{D}

---

docs/src/tutorial.md

`kill_agent!` is no more, reference `remove_agent!` in its stead.
Also fixed some minor grammar issues I came across, and made the YouTube link clickable.

Doc: Function name fix in tutorial.md (+ minor grammar fixes)

---

CHANGELOG.md
src/core/model_abstract.jl
src/spaces/continuous.jl
src/spaces/grid_general.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl
src/spaces/utilities.jl
src/spaces/walk.jl
src/submodules/pathfinding/astar.jl
src/submodules/pathfinding/astar_continuous.jl
src/submodules/pathfinding/pathfinding_utils.jl
test/astar_tests.jl
test/grid_space_tests.jl

Closes #828.
WIP, there are still a lot of things to fix.
I tried to represent space periodicity with a new type `Periodic{D}` to only be used internally, which would just wrap a SVector with a Bool value for each spatial dimension. When given a `Bool` e.g. `Periodic{D}(true)` it is internally converted to a SVector as `fill(true, SVector{D})`.
I don't have a smart way to fall back to "full periodic" and "non periodic" via dispatch yet, so as it is now every time distances have to be evaluated, each dimensions needs to be checked for whether or not it is periodic. In low-dimensional systems (which I assume make up the vast majority of use cases) there is no performance difference; in high-dimensional ones it might start to become noticeable (although I don't know to what extent this is …

Mixed boundary conditions

---

CHANGELOG.md
docs/src/comparison.md
examples/flock.jl
src/Agents.jl

this fixes the Flocking example and improves the changelog for v6

Docs Updates

---

src/spaces/grid_general.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl
src/submodules/io/jld2_integration.jl
src/submodules/pathfinding/astar.jl

create extent attr for GridSpaces

---

docs/src/comparison.md

Probably still too many details are mentioned here.  Still the comparison repo doesn't have LOCs calculation, but will add them soon.

Remove comparison table and just direct to comparison repository

---

ext/AgentsVisualizations/src/inspection.jl

Tooltips for agent inspection have been broken for a while now and this PR should fix this bug. Inspection was tested for the models included in `Agents.Models`, specifically I tested `schelling`, `flocking`, `daisyworld`, and `zombies`. I did not test any 3D models.

Fix inspection tooltips

---

src/spaces/grid_general.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl
src/submodules/io/jld2_integration.jl

This should make the retrieval of the offsets faster.....
The PR removes the dictionaries used to hold the offsets for calculating nearby stuff and substitute them with vectors. The access to a vector should be faster, and so this should help performance
Still needs benchmarks

Use Vectors instead of a Dict for nearby offsets

---

src/Agents.jl
src/core/space_interaction_API.jl

This will fail with an easy to bisect error anyway since adding to the model will fail since the agent type will not be accepted. Forgot to do it when merging #900

Remove unnecessary check in add_agent_pos!

---

.gitignore
ext/AgentsArrow/AgentsArrow.jl
src/simulations/collect.jl
test/collect_tests.jl

Actually there are current problems with tempfile locking in Windows for Arrow.jl, indeed some tests are not enabled in Arrow.jl for Windows in that repo. I also remembered that offline_run! worked fine for me, there was just a problem in deleting the file during tests but not when using from the external of the package (now I understand that this is due to this locking problem). So I think that we can anyway enable the backend also in Windows so that users can benefit from it.
See https://github.com/apache/arrow-julia/pull/361

Enable arrow backend for offline_run! in Windows

---

CHANGELOG.md
src/core/space_interaction_API.jl

This is faster, as some benchmark show, same code and metodology of #788 
before
```julia
julia> @benchmark random_nearby_position($(50,50), $model, $1)
BenchmarkTools.Trial: 10000 samples with 958 evaluations.
Range (min … max):   94.749 ns …  1.410 μs  ┊ GC (min … max): 0.00% … 90.62%
Time  (median):     100.439 ns              ┊ GC (median):    0.00%
Time  (mean ± σ):   102.630 ns ± 32.078 ns  ┊ GC (mean ± σ):  0.74% ±  2.21%
▁▄▇▇██▆▃▁                                          
▁▁▁▁▁▁▂▂▃▅▇█████████▇▅▄▃▃▃▃▂▂▂▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▃▃▂▂▂▂▂▂▂▁▂▁ ▃
94.7 ns         Histogram: frequency by time          115 ns <
Memory estimate: 32 bytes, allocs estimate: 1.
julia> @benchmark random_nearby_position($(50,50), $model, $10)
BenchmarkTools.Trial: 10000 samples with 182 evaluations.
Range (min … max): …
```

Faster reservoir sampling

---

src/core/model_single_container.jl
src/core/space_interaction_API.jl
src/simulations/sample.jl
src/spaces/continuous.jl
src/spaces/discrete.jl
src/spaces/utilities.jl
src/submodules/io/csv_integration.jl
src/submodules/pathfinding/astar.jl
src/submodules/pathfinding/astar_continuous.jl
src/submodules/pathfinding/astar_grid.jl

Will do a pass of the library to simplify signatures for #915 . Still need to look at the most part of the library

Simplify signatures

---

CHANGELOG.md
src/spaces/grid_multi.jl

This reduces the allocations of the iterator.
As you can see on this Flocking benchmark inside the ABMFrameworkComparison repo the speed improvement is nice:
```julia
#before
julia> a = @benchmark run_model(rng, (150, 150), 400, 15.0) setup = (rng = rng_model()) evals=1 samples=n_run seconds=1e6
BenchmarkTools.Trial: 100 samples with 1 evaluation.
Range (min … max):  37.952 ms … 61.669 ms  ┊ GC (min … max): 5.92% … 8.08%
Time  (median):     47.160 ms              ┊ GC (median):    7.55%
Time  (mean ± σ):   47.599 ms ±  4.318 ms  ┊ GC (mean ± σ):  7.46% ± 1.12%
▆   ▂▆  █▄ █  ▄ ▂                              
▄▄▁▁▄▁▁▁█▁▆▆▄██▆█▆██▆▄██▆█▆██▄██▄▆█▄▆▁▆▁▁▆█▁▄▁▆▁▁▁▁▁▁▁▁▁▁▁▄ ▄
38 ms           Histogram: frequency by time          61 ms <
Memory estimate: 98.61 MiB, allocs estimate: 2151950.
#after …
```

Use a mutable struct for the state of GridSpaceIdIterator

---

docs/logo/example_zoo.jl
src/core/agents.jl
test/visualization_tests.jl

Remove ) causing parse error in example_zoo.jl

---

src/deprecations.jl

This is useful for some deprecated methods, otherwise they break things given the new updates

add versions of until for deprecated methods

---

examples/agents_visualizations.jl
test/runtests.jl

Since #875 has some problems I do this separately, see https://github.com/JuliaDynamics/Agents.jl/pull/875#issuecomment-1891054174 for why we need this
edit: actually #875 is fine because also #946 has the same errors, but both work locally. However, let's merge this separately anyway since it is more sensible anyway

Handle compatibility with dev version of AgentsExampleZoo better

---

CHANGELOG.md
docs/src/api.md
src/core/model_abstract.jl
src/core/model_accessing_API.jl
src/core/model_standard.jl
src/deprecations.jl
src/simulations/step.jl
src/submodules/schedulers.jl
test/api_tests.jl

- All docstrings have been made "correct": they refer to ordering, and not scheduling, and they refer to the IDs, not the agents
- Deprecated using `schedule` with the non-default scheduler, as all schedulers are anyways functions of the model, there is no need to pipe them through `schedule`.
- Highlighted another usage for the schedulers
- Remove wording "once per step" from schedulers: this is clear from the `StandardABM` docstring. Furthermore, how many times scheduling happens in custom scheduling is unknown.

Improve `Schedulers` docs

---

src/core/model_free_extensions.jl
src/core/space_interaction_API.jl
src/spaces/discrete.jl
src/spaces/walk.jl

`:alg_R` is like 5x faster for small iterators than `:alg_L`, but slower with larger ones. So I applied one or the other depending on the probable scenario

Faster sampling from small iterators

---

test/performance/variable_agent_types_simple_dynamics.jl

now at https://juliadynamics.github.io/Agents.jl/previews/PR988/performance_tips/:

Benchmark also multiagent with less than 15 types

---

src/core/model_accessing_API.jl
src/core/model_standard.jl

Just realized it is needed for #992 thread safe dict

Enlarge DictABM and VecABM for dispatch

---

examples/rabbit_fox_hawk.jl
ext/AgentsVisualizations/src/abmplot.jl
ext/AgentsVisualizations/src/spaces/abstract.jl

Fix Makie issues

---

examples/agents_visualizations.jl
examples/celllistmap.jl
examples/flock.jl
examples/predator_prey.jl
examples/rabbit_fox_hawk.jl
examples/schoolyard.jl
examples/zombies.jl
ext/AgentsVisualizations/src/abmplot.jl
ext/AgentsVisualizations/src/deprecations.jl
ext/AgentsVisualizations/src/utils.jl
src/visualizations.jl

Deprecate `as, am, ac` in favor of  `agent_size, agent_marker, agent_color`

---

examples/agents_visualizations.jl
ext/AgentsVisualizations/src/convenience.jl
ext/AgentsVisualizations/src/interaction.jl
ext/AgentsVisualizations/src/model_observable.jl
ext/AgentsVisualizations/src/spaces/abstract.jl
src/simulations/collect.jl
src/visualizations.jl

Fix reset button in abmexploration

---

Project.toml
examples/event_rock_paper_scissors.jl
src/core/agents.jl
src/core/model_event_queue.jl
src/simulations/step_eventqueue.jl

This makes RPS more than 2x faster! in general a `Heap` is more suitable than a `PriorityQueue` for this task, also it actually makes everything better because a `PriorityQueue` denied the use of duplicate times, which is actually something which could happen

Use Heap instead of PriorityQueue in EventQueueABM

---

Project.toml
docs/Project.toml
docs/src/index.md

This way we signal (a bit) the version with which the integration surely works for users, because if a major version is made could be problematic if the docs are not updated

Specify versions for Integration Libraries in Docs Project.toml

---

Project.toml
src/spaces/graph.jl

We forgot to do this during transition to version 6 :( But they were deprecated in v5 so it can be fixed this way

Remove deprecated methods in version 5 rem_node!, add_node!

---

Project.toml
src/spaces/openstreetmap.jl
test/osm_tests.jl

It is possible to plan a route to a destination `dest` for which `dest[3]` is not between zero and `road_length(dest[1], dest[2], model)`, which is not caught by the subsequent shortest path algorithm. When such a route is executed, the agent will snap to a position that is not on the graph after completing the route.
With this PR, we check that the destination is valid and if it is not, we exit the `plan_route!` function early and return `false`.
Discovered in #1023.

Add OSM destination check

---

docs/Project.toml
examples/celllistmap.jl

This updates the CellListMap integration example to use the renamed `ParticleSystem` syntax, which was introduced in version 0.9.0 and will become the standard in a future 1.0 release. No functionality was changed.

Update celllistmap.jl example

---

Project.toml
examples/sir.jl

This fixes the SIR example for me. 
Might fix https://github.com/JuliaDynamics/Agents.jl/issues/1026

fix SIR example

---

Project.toml
docs/src/api.md
src/submodules/schedulers.jl
test/scheduler_tests.jl

Fixes https://github.com/JuliaDynamics/Agents.jl/issues/1014

Implement ByKind scheduler

---

src/core/agents.jl

The field isn't declared as a const

Fix typo in `@agent` docstring

---

src/core/model_abstract.jl
src/core/model_accessing_API.jl
src/simulations/collect.jl
src/simulations/step.jl
src/spaces/grid_multi.jl
src/spaces/grid_single.jl
test/visualization_tests.jl

These changes make JET a bit happier about the package

Fix some (innocuous) dynamic dispatches

---

Project.toml
src/Agents.jl
src/core/model_event_queue.jl

before
```julia
julia> model = initialize_rps();
julia> @benchmark step!($model)
BenchmarkTools.Trial: 10000 samples with 197 evaluations.
Range (min … max):  426.081 ns …  56.132 μs  ┊ GC (min … max): 0.00% … 98.59%
Time  (median):     471.038 ns               ┊ GC (median):    0.00%
Time  (mean ± σ):   512.019 ns ± 745.854 ns  ┊ GC (mean ± σ):  5.40% ±  4.60%
▂▄▆▇█▇▆▄▃▁                                              
▁▁▂▃▄▅████████████▆▅▃▃▃▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁ ▃
426 ns           Histogram: frequency by time          641 ns <
Memory estimate: 378 bytes, allocs estimate: 7.
```
after
```julia
julia> model = initialize_rps();
julia> @benchmark step!($model)
BenchmarkTools.Trial: 10000 samples with 207 evaluations.
Range (min … max):  343.237 ns …  46.423 μs  ┊ GC (min … …
```

Improve performance of EventQueueABM by better union splitting

---

Project.toml
src/core/model_event_queue.jl

This shaves away another bit (5%) of overhead of the event queue implementation: now the implementation is almost free in terms of overhead, only the queue insertion and removal take some time (1/3 of total) in RPS, which is probably unavoidable

Avoid using a Dict for index retrieval with multiagent macro

---

Project.toml
src/core/model_event_queue.jl

Another 10% of time shaved with this, I think that's it for now :D

Use a faster ordering for heap in EventQueueABM

---

docs/src/api.md

In Step 1 of https://juliadynamics.github.io/Agents.jl/stable/tutorial/, it links to https://juliadynamics.github.io/Agents.jl/stable/tutorial/@ref%20available_spaces in the sentence "Agents.jl offers multiple spaces one can utilize to perform simulations, all of which are listed in the [available spaces section](https://juliadynamics.github.io/Agents.jl/stable/tutorial/@ref%20available_spaces).". This link is broken since the intended reference is using `@ref` instead of `@id`.

Fix broken link in documentation

---

docs/src/tutorial.md
src/spaces/continuous.jl

Just some very tiny edits to fix spelling and readability.

docs: Small grammar edits

---

examples/agents_visualizations.jl

I think this warning is probably outdated now that Makie does do kwarg checking?

Remove outdated warning about kwargs

---

examples/agents_visualizations.jl

Reverts JuliaDynamics/Agents.jl#1084
Actually I'm wrong @Datseris, the warning is outdated _if_ it refers to typos inside `agentsplotkwargs` or `spaceplotkwargs`, but not if there are typos for kwargs to `abmplot` itself (e.g. `agentplotkwargs` instead of `agentsplotkwargs` won't warn...) I guess just keep it for now.

Revert "Remove outdated warning about kwargs"

---

docs/src/devdocs.md
src/core/model_standard.jl
src/spaces/discrete.jl
test/new_space_tests.jl
test/runtests.jl

This fixes #1104.
- Restrict the method in discrete.jl to discrete spaces
- Add a test that defines a new space as described in the dev docs and checks that adding and removing agents works. The test fails without the next step
- Add a generic fallback that makes the new test pass
- Add a note in the dev docs that this is a candidate to be overloaded for performance

Fix dispatch for `remove_all_from_space!`

---

CHANGELOG.md
Project.toml
docs/src/api.md
src/core/model_event_queue.jl

I guess we should do this now?

Remove "experimental" from continuous time

---

src/core/model_event_queue.jl
src/core/model_standard.jl
src/simulations/sample.jl
test/scheduler_tests.jl

Not needed anymore since we are abandoning the previous methodology for multiagent systems

Remove ismultiagenttype checks

---

docs/src/tutorial.jl

line 603 in docs/src/tutorial.jl
changed from
```julia
figure, _ = abmplot(model; agent_color = groupcolor, agent_marker = groupmarker, as = 10) # not executing
```
to
```julia
figure, _ = abmplot(schelling; agent_color = groupcolor, agent_marker = groupmarker, agent_size = 10)
```

line 603, 'schelling' instead of 'model'

---

Project.toml
examples/rabbit_fox_hawk.jl

Per the conversation in https://github.com/JuliaDynamics/Agents.jl/issues/1118
I have added the line 
```julia
animalcolor(animal) = animalcolor(animal, variant(animal))
```

Added line to rabbit_fox_hawk.jl to make animation run and fix #1118

---

Project.toml
examples/rabbit_fox_hawk.jl

Fix wrong dispatch in example

---

examples/diffeq.jl

In this tutorial https://github.com/JuliaDynamics/Agents.jl/issues/1133 the figure call uses resolution over size.
I have updated this file only: https://juliadynamics.github.io/Agents.jl/stable/examples/diffeq/

Integrating Agents.jl with DifferentialEquations.jl Makie Figure call uses resolution over size

---

Project.toml
docs/src/api.md
src/core/model_standard.jl
src/simulations/step.jl
src/spaces/graph.jl
src/spaces/openstreetmap.jl
src/spaces/utilities.jl
src/submodules/schedulers.jl

Partially fix #1142
Don't know how to fix:
```
89:6664: gent &lt;: AbstractAgent</code></pre><p>The minimal agent struct for usage with <a href="@ref OSM.OpenStreetMapSpace"><code>OpenStreetMapSpace</code></a>. It has an additional field <code>pos::
95:697: , as an agent can truly be at any possible point on an existing road.</p><p>Use <a href="@ref OSM.OSMAgent"><code>OSMAgent</code></a> for convenience.</p><p><strong>Obtaining map files</strong>
131:4193: his map requires <code>network_type = :none</code> to be passed as a keyword to <a href="@ref OSM.OpenStreetMapSpace"><code>OpenStreetMapSpace</code></a>. The unit of distance used for this map
```
Not sure about the missing docstring for `isempty` and the resulting broken link:
`125:1191: position</code></a>, but specialized for …

Fix links (second round)

---

src/spaces/grid_general.jl

I was a bit upset by the fact that our game of life at https://juliadynamics.github.io/AgentsExampleZoo.jl/dev/examples/game_of_life_2D_CA/#Conway's-game-of-life allocated, with this allocations disappear completely and the model is 2x faster

Improve performance of nearby_positions for GridSpaces
